# Generated by Django 5.1.4 on 2024-12-28 09:22

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
    ]
